### ISSUE TITLE
Task List #1

### ISSUE THREAD

**Issue by Diacod-I** [Diacod-I/BourneToKill#3]
- [x] - Change the order of Lipinksi Descriptors' visualizations and add more summaries.
- [ ] - Incorporate the PADME software somehow (otherwise look for alternatives)
- [ ] - Perform more statistical tests like normality tests and contingency table analysis
